import BaseQueryExpression from "./query/_baseClasses/BaseQueryExpression.js";
import { eq, gt, gte, lt, lte, notEq } from "./query/comparisons/_basicColumnComparisonOperation.js";
import { between, notBetween } from "./query/comparisons/_betweenColumnComparisonOperation.js";
import sqlIn from "./query/comparisons/in.js";
import isNotNull from "./query/comparisons/isNotNull.js";
import isNull from "./query/comparisons/isNull.js";
import like from "./query/comparisons/like.js";
import sqlNotIn from "./query/comparisons/notIn.js";
import notLike from "./query/comparisons/notLike.js";

BaseQueryExpression.prototype.eq = eq;
BaseQueryExpression.prototype.notEq = notEq;
BaseQueryExpression.prototype.gt = gt;
BaseQueryExpression.prototype.gte = gte;
BaseQueryExpression.prototype.lt = lt;
BaseQueryExpression.prototype.lte = lte;
BaseQueryExpression.prototype.between = between;
BaseQueryExpression.prototype.notBetween = notBetween;
BaseQueryExpression.prototype.sqlIn = sqlIn;
BaseQueryExpression.prototype.sqlNotIn = sqlNotIn;
BaseQueryExpression.prototype.like = like;
BaseQueryExpression.prototype.notLike = notLike;
BaseQueryExpression.prototype.isNull = isNull;
BaseQueryExpression.prototype.isNotNull = isNotNull;
