import BaseQueryExpression from "./query/_baseClasses/BaseQueryExpression.js";
import { eq, gt, gte, lt, lte, notEq } from "./query/comparisons/_basicColumnComparisonOperation.js";
import { between, notBetween } from "./query/comparisons/_betweenColumnComparisonOperation.js";
import { sqlIn, sqlNotIn } from "./query/comparisons/_inColumnComparisonOperation.js";
import { isNotNull, isNull } from "./query/comparisons/_isNullColumnComparisonOperation.js";
import { iLike, like, notILike, notLike } from "./query/comparisons/_likeColumnComparisonOperation.js";
import QueryBuilder from "./query/queryBuilder.js";

BaseQueryExpression.prototype.eq = eq;
BaseQueryExpression.prototype.notEq = notEq;
BaseQueryExpression.prototype.gt = gt;
BaseQueryExpression.prototype.gte = gte;
BaseQueryExpression.prototype.lt = lt;
BaseQueryExpression.prototype.lte = lte;
BaseQueryExpression.prototype.between = between;
BaseQueryExpression.prototype.notBetween = notBetween;
BaseQueryExpression.prototype.sqlIn = sqlIn;
BaseQueryExpression.prototype.sqlNotIn = sqlNotIn;
BaseQueryExpression.prototype.isNull = isNull;
BaseQueryExpression.prototype.isNotNull = isNotNull;
BaseQueryExpression.prototype.like = like;
BaseQueryExpression.prototype.notLike = notLike;
BaseQueryExpression.prototype.iLike = iLike;
BaseQueryExpression.prototype.notILike = notILike;